// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTiemChung_MVC_DOTNET.Models;

namespace QuanLyTiemChung_MVC_DOTNET.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.Benh", b =>
                {
                    b.Property<string>("MaBenh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBenh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBenh");

                    b.ToTable("Benhs");
                });

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChiKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTenKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.LichSuTiemPhong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KhachHangsMaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaVacXin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayHenTiepTheo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiemPhong")
                        .HasColumnType("datetime2");

                    b.Property<string>("STTMui")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VacXinsMaVacXin")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("KhachHangsMaKH");

                    b.HasIndex("VacXinsMaVacXin");

                    b.ToTable("LichSuTiemPhongs");
                });

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.PhongBenh", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BenhsMaBenh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBenh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaVacXin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VacXinsMaVacXin")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("BenhsMaBenh");

                    b.HasIndex("VacXinsMaVacXin");

                    b.ToTable("PhongBenhs");
                });

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.User", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.HasIndex("MaKH")
                        .IsUnique()
                        .HasFilter("[MaKH] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.VacXin", b =>
                {
                    b.Property<string>("MaVacXin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoMui")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVacXin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVacXin");

                    b.ToTable("VacXins");
                });

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.LichSuTiemPhong", b =>
                {
                    b.HasOne("QuanLyTiemChung_MVC_DOTNET.Models.KhachHang", "KhachHangs")
                        .WithMany("VacXins")
                        .HasForeignKey("KhachHangsMaKH");

                    b.HasOne("QuanLyTiemChung_MVC_DOTNET.Models.VacXin", "VacXins")
                        .WithMany("KhachHangs")
                        .HasForeignKey("VacXinsMaVacXin");
                });

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.PhongBenh", b =>
                {
                    b.HasOne("QuanLyTiemChung_MVC_DOTNET.Models.Benh", "Benhs")
                        .WithMany("VacXins")
                        .HasForeignKey("BenhsMaBenh");

                    b.HasOne("QuanLyTiemChung_MVC_DOTNET.Models.VacXin", "VacXins")
                        .WithMany("Benhs")
                        .HasForeignKey("VacXinsMaVacXin");
                });

            modelBuilder.Entity("QuanLyTiemChung_MVC_DOTNET.Models.User", b =>
                {
                    b.HasOne("QuanLyTiemChung_MVC_DOTNET.Models.KhachHang", "KhachHang")
                        .WithOne("User")
                        .HasForeignKey("QuanLyTiemChung_MVC_DOTNET.Models.User", "MaKH");
                });
#pragma warning restore 612, 618
        }
    }
}
